os: linux
services:
    - docker
sudo: required
language: minimal

jobs:
    include:
        - stage: compile
          name: "GCC 8"
          script: docker run -v$(pwd):/home/conan conanio/gcc8 bash -c "cmake/scripts/build_travis.sh"
        - script: docker run -v$(pwd):/home/conan conanio/clang7 bash -c "cmake/scripts/build_travis.sh"
          name: "Clang 7"
        - script: docker run -v$(pwd):/src trzeci/emscripten bash -c "cmake/scripts/build_travis_web.sh"
          name: "Emscripten"
          deploy:
            provider: pages
            skip-cleanup: true
            github-token: $GITHUB_TOKEN
            local-dir: src/web
