version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: >-
    echo "Downloading conan..."

    set PATH=%PATH%;%PYTHON%/Scripts/

    pip.exe install conan

    conan user # Create the conan data directory

    conan --version
install:
- cmd: 
build_script:
- cmd: >-
    mkdir build_cmake

    cd build_cmake

    cmake ../ -G "Visual Studio 15 2017 Win64"

    cmake --build . --config Release