#pragma once

#include "cpu.h"

namespace gbhw
{
	inline void initialise_instructions(Instruction* instructions)
	{
		instructions[ 0x0].set( 0x0,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "NOP");
		instructions[ 0x1].set( 0x1,  0x0, 3, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::BC,     RTD::Imm16 , "LD BC,d16");
		instructions[ 0x2].set( 0x2,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrBC, RTD::A     , "LD (BC),A");
		instructions[ 0x3].set( 0x3,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::BC,     RTD::None  , "INC BC");
		instructions[ 0x4].set( 0x4,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::B,      RTD::None  , "INC B");
		instructions[ 0x5].set( 0x5,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::B,      RTD::None  , "DEC B");
		instructions[ 0x6].set( 0x6,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::Imm8  , "LD B,d8");
		instructions[ 0x7].set( 0x7,  0x0, 1,  4,  0, RFB::Reset,       RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::None,   RTD::None  , "RLCA");
		instructions[ 0x8].set( 0x8,  0x0, 3, 20,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Addr16, RTD::SP    , "LD a16,SP");
		instructions[ 0x9].set( 0x9,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::HL,     RTD::BC    , "ADD HL,BC");
		instructions[ 0xa].set( 0xa,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::AddrBC, "LD A,(BC)");
		instructions[ 0xb].set( 0xb,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::BC,     RTD::None  , "DEC BC");
		instructions[ 0xc].set( 0xc,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::C,      RTD::None  , "INC C");
		instructions[ 0xd].set( 0xd,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::C,      RTD::None  , "DEC C");
		instructions[ 0xe].set( 0xe,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::Imm8  , "LD C,d8");
		instructions[ 0xf].set( 0xf,  0x0, 1,  4,  0, RFB::Reset,       RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::None,   RTD::None  , "RRCA");
		instructions[0x10].set(0x10,  0x0, 2,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::None  , "STOP 0");
		instructions[0x11].set(0x11,  0x0, 3, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::DE,     RTD::Imm16 , "LD DE,d16");
		instructions[0x12].set(0x12,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrDE, RTD::A     , "LD (DE),A");
		instructions[0x13].set(0x13,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::DE,     RTD::None  , "INC DE");
		instructions[0x14].set(0x14,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::D,      RTD::None  , "INC D");
		instructions[0x15].set(0x15,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::D,      RTD::None  , "DEC D");
		instructions[0x16].set(0x16,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::Imm8  , "LD D,d8");
		instructions[0x17].set(0x17,  0x0, 1,  4,  0, RFB::Reset,       RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::None,   RTD::None  , "RLA");
		instructions[0x18].set(0x18,  0x0, 2, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::SImm8,  RTD::None  , "JR r8");
		instructions[0x19].set(0x19,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::HL,     RTD::DE    , "ADD HL,DE");
		instructions[0x1a].set(0x1a,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::AddrDE, "LD A,(DE)");
		instructions[0x1b].set(0x1b,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::DE,     RTD::None  , "DEC DE");
		instructions[0x1c].set(0x1c,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::E,      RTD::None  , "INC E");
		instructions[0x1d].set(0x1d,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::E,      RTD::None  , "DEC E");
		instructions[0x1e].set(0x1e,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::Imm8  , "LD E,d8");
		instructions[0x1f].set(0x1f,  0x0, 1,  4,  0, RFB::Reset,       RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::None,   RTD::None  , "RRA");
		instructions[0x20].set(0x20,  0x0, 2, 12,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNZ, RTD::SImm8 , "JR NZ,r8");
		instructions[0x21].set(0x21,  0x0, 3, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::HL,     RTD::Imm16 , "LD HL,d16");
		instructions[0x22].set(0x22,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::A     , "LDI (HL),A");
		instructions[0x23].set(0x23,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::HL,     RTD::None  , "INC HL");
		instructions[0x24].set(0x24,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::H,      RTD::None  , "INC H");
		instructions[0x25].set(0x25,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::H,      RTD::None  , "DEC H");
		instructions[0x26].set(0x26,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::Imm8  , "LD H,d8");
		instructions[0x27].set(0x27,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Unmodified,  RFB::Reset,       RFB::PerFunction , RTD::None,   RTD::None  , "DAA");
		instructions[0x28].set(0x28,  0x0, 2, 12,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagZ,  RTD::SImm8 , "JR Z,r8");
		instructions[0x29].set(0x29,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::HL,     RTD::HL    , "ADD HL,HL");
		instructions[0x2a].set(0x2a,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::AddrHL, "LDI A,(HL)");
		instructions[0x2b].set(0x2b,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::HL,     RTD::None  , "DEC HL");
		instructions[0x2c].set(0x2c,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::L,      RTD::None  , "INC L");
		instructions[0x2d].set(0x2d,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::L,      RTD::None  , "DEC L");
		instructions[0x2e].set(0x2e,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::Imm8  , "LD L,d8");
		instructions[0x2f].set(0x2f,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Set,         RFB::Set,         RFB::Unmodified  , RTD::None,   RTD::None  , "CPL");
		instructions[0x30].set(0x30,  0x0, 2, 12,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNC, RTD::SImm8 , "JR NC,r8");
		instructions[0x31].set(0x31,  0x0, 3, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::SP,     RTD::Imm16 , "LD SP,d16");
		instructions[0x32].set(0x32,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::A     , "LDD (HL),A");
		instructions[0x33].set(0x33,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::SP,     RTD::None  , "INC SP");
		instructions[0x34].set(0x34,  0x0, 1, 12,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::AddrHL, RTD::None  , "INC (HL)");
		instructions[0x35].set(0x35,  0x0, 1, 12,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::AddrHL, RTD::None  , "DEC (HL)");
		instructions[0x36].set(0x36,  0x0, 2, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::Imm8  , "LD (HL),d8");
		instructions[0x37].set(0x37,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Reset,       RFB::Reset,       RFB::Set         , RTD::None,   RTD::None  , "SCF");
		instructions[0x38].set(0x38,  0x0, 2, 12,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagC,  RTD::SImm8 , "JR CF,r8");
		instructions[0x39].set(0x39,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::HL,     RTD::SP    , "ADD HL,SP");
		instructions[0x3a].set(0x3a,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::AddrHL, "LDD A,(HL)");
		instructions[0x3b].set(0x3b,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::SP,     RTD::None  , "DEC SP");
		instructions[0x3c].set(0x3c,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::Unmodified  , RTD::A,      RTD::None  , "INC A");
		instructions[0x3d].set(0x3d,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::Unmodified  , RTD::A,      RTD::None  , "DEC A");
		instructions[0x3e].set(0x3e,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::Imm8  , "LD A,d8");
		instructions[0x3f].set(0x3f,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::None,   RTD::None  , "CCF");
		instructions[0x40].set(0x40,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::B     , "LD B,B");
		instructions[0x41].set(0x41,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::C     , "LD B,C");
		instructions[0x42].set(0x42,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::D     , "LD B,D");
		instructions[0x43].set(0x43,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::E     , "LD B,E");
		instructions[0x44].set(0x44,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::H     , "LD B,H");
		instructions[0x45].set(0x45,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::L     , "LD B,L");
		instructions[0x46].set(0x46,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::AddrHL, "LD B,(HL)");
		instructions[0x47].set(0x47,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::B,      RTD::A     , "LD B,A");
		instructions[0x48].set(0x48,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::B     , "LD C,B");
		instructions[0x49].set(0x49,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::C     , "LD C,C");
		instructions[0x4a].set(0x4a,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::D     , "LD C,D");
		instructions[0x4b].set(0x4b,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::E     , "LD C,E");
		instructions[0x4c].set(0x4c,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::H     , "LD C,H");
		instructions[0x4d].set(0x4d,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::L     , "LD C,L");
		instructions[0x4e].set(0x4e,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::AddrHL, "LD C,(HL)");
		instructions[0x4f].set(0x4f,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::C,      RTD::A     , "LD C,A");
		instructions[0x50].set(0x50,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::B     , "LD D,B");
		instructions[0x51].set(0x51,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::C     , "LD D,C");
		instructions[0x52].set(0x52,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::D     , "LD D,D");
		instructions[0x53].set(0x53,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::E     , "LD D,E");
		instructions[0x54].set(0x54,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::H     , "LD D,H");
		instructions[0x55].set(0x55,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::L     , "LD D,L");
		instructions[0x56].set(0x56,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::AddrHL, "LD D,(HL)");
		instructions[0x57].set(0x57,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::D,      RTD::A     , "LD D,A");
		instructions[0x58].set(0x58,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::B     , "LD E,B");
		instructions[0x59].set(0x59,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::C     , "LD E,C");
		instructions[0x5a].set(0x5a,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::D     , "LD E,D");
		instructions[0x5b].set(0x5b,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::E     , "LD E,E");
		instructions[0x5c].set(0x5c,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::H     , "LD E,H");
		instructions[0x5d].set(0x5d,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::L     , "LD E,L");
		instructions[0x5e].set(0x5e,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::AddrHL, "LD E,(HL)");
		instructions[0x5f].set(0x5f,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::E,      RTD::A     , "LD E,A");
		instructions[0x60].set(0x60,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::B     , "LD H,B");
		instructions[0x61].set(0x61,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::C     , "LD H,C");
		instructions[0x62].set(0x62,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::D     , "LD H,D");
		instructions[0x63].set(0x63,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::E     , "LD H,E");
		instructions[0x64].set(0x64,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::H     , "LD H,H");
		instructions[0x65].set(0x65,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::L     , "LD H,L");
		instructions[0x66].set(0x66,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::AddrHL, "LD H,(HL)");
		instructions[0x67].set(0x67,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::H,      RTD::A     , "LD H,A");
		instructions[0x68].set(0x68,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::B     , "LD L,B");
		instructions[0x69].set(0x69,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::C     , "LD L,C");
		instructions[0x6a].set(0x6a,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::D     , "LD L,D");
		instructions[0x6b].set(0x6b,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::E     , "LD L,E");
		instructions[0x6c].set(0x6c,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::H     , "LD L,H");
		instructions[0x6d].set(0x6d,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::L     , "LD L,L");
		instructions[0x6e].set(0x6e,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::AddrHL, "LD L,(HL)");
		instructions[0x6f].set(0x6f,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::L,      RTD::A     , "LD L,A");
		instructions[0x70].set(0x70,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::B     , "LD (HL),B");
		instructions[0x71].set(0x71,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::C     , "LD (HL),C");
		instructions[0x72].set(0x72,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::D     , "LD (HL),D");
		instructions[0x73].set(0x73,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::E     , "LD (HL),E");
		instructions[0x74].set(0x74,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::H     , "LD (HL),H");
		instructions[0x75].set(0x75,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::L     , "LD (HL),L");
		instructions[0x76].set(0x76,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "HALT");
		instructions[0x77].set(0x77,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::A     , "LD (HL),A");
		instructions[0x78].set(0x78,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::B     , "LD A,B");
		instructions[0x79].set(0x79,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::C     , "LD A,C");
		instructions[0x7a].set(0x7a,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::D     , "LD A,D");
		instructions[0x7b].set(0x7b,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::E     , "LD A,E");
		instructions[0x7c].set(0x7c,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::H     , "LD A,H");
		instructions[0x7d].set(0x7d,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::L     , "LD A,L");
		instructions[0x7e].set(0x7e,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::AddrHL, "LD A,(HL)");
		instructions[0x7f].set(0x7f,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::A     , "LD A,A");
		instructions[0x80].set(0x80,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::B     , "ADD A,B");
		instructions[0x81].set(0x81,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::C     , "ADD A,C");
		instructions[0x82].set(0x82,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::D     , "ADD A,D");
		instructions[0x83].set(0x83,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::E     , "ADD A,E");
		instructions[0x84].set(0x84,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::H     , "ADD A,H");
		instructions[0x85].set(0x85,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::L     , "ADD A,L");
		instructions[0x86].set(0x86,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::AddrHL, "ADD A,(HL)");
		instructions[0x87].set(0x87,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::A     , "ADD A,A");
		instructions[0x88].set(0x88,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::B     , "ADC A,B");
		instructions[0x89].set(0x89,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::C     , "ADC A,C");
		instructions[0x8a].set(0x8a,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::D     , "ADC A,D");
		instructions[0x8b].set(0x8b,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::E     , "ADC A,E");
		instructions[0x8c].set(0x8c,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::H     , "ADC A,H");
		instructions[0x8d].set(0x8d,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::L     , "ADC A,L");
		instructions[0x8e].set(0x8e,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::AddrHL, "ADC A,(HL)");
		instructions[0x8f].set(0x8f,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::A     , "ADC A,A");
		instructions[0x90].set(0x90,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::B,      RTD::None  , "SUB B");
		instructions[0x91].set(0x91,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::C,      RTD::None  , "SUB C");
		instructions[0x92].set(0x92,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::D,      RTD::None  , "SUB D");
		instructions[0x93].set(0x93,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::E,      RTD::None  , "SUB E");
		instructions[0x94].set(0x94,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::H,      RTD::None  , "SUB H");
		instructions[0x95].set(0x95,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::L,      RTD::None  , "SUB L");
		instructions[0x96].set(0x96,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::AddrHL, RTD::None  , "SUB (HL)");
		instructions[0x97].set(0x97,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::None  , "SUB A");
		instructions[0x98].set(0x98,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::B     , "SBC A,B");
		instructions[0x99].set(0x99,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::C     , "SBC A,C");
		instructions[0x9a].set(0x9a,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::D     , "SBC A,D");
		instructions[0x9b].set(0x9b,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::E     , "SBC A,E");
		instructions[0x9c].set(0x9c,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::H     , "SBC A,H");
		instructions[0x9d].set(0x9d,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::L     , "SBC A,L");
		instructions[0x9e].set(0x9e,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::AddrHL, "SBC A,(HL)");
		instructions[0x9f].set(0x9f,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::A     , "SBC A,A");
		instructions[0xa0].set(0xa0,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::B,      RTD::None  , "AND B");
		instructions[0xa1].set(0xa1,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::C,      RTD::None  , "AND C");
		instructions[0xa2].set(0xa2,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::D,      RTD::None  , "AND D");
		instructions[0xa3].set(0xa3,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::E,      RTD::None  , "AND E");
		instructions[0xa4].set(0xa4,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::H,      RTD::None  , "AND H");
		instructions[0xa5].set(0xa5,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::L,      RTD::None  , "AND L");
		instructions[0xa6].set(0xa6,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::AddrHL, RTD::None  , "AND (HL)");
		instructions[0xa7].set(0xa7,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::A,      RTD::None  , "AND A");
		instructions[0xa8].set(0xa8,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::B,      RTD::None  , "XOR B");
		instructions[0xa9].set(0xa9,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::C,      RTD::None  , "XOR C");
		instructions[0xaa].set(0xaa,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::D,      RTD::None  , "XOR D");
		instructions[0xab].set(0xab,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::E,      RTD::None  , "XOR E");
		instructions[0xac].set(0xac,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::H,      RTD::None  , "XOR H");
		instructions[0xad].set(0xad,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::L,      RTD::None  , "XOR L");
		instructions[0xae].set(0xae,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::AddrHL, RTD::None  , "XOR (HL)");
		instructions[0xaf].set(0xaf,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::A,      RTD::None  , "XOR A");
		instructions[0xb0].set(0xb0,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::B,      RTD::None  , "OR B");
		instructions[0xb1].set(0xb1,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::C,      RTD::None  , "OR C");
		instructions[0xb2].set(0xb2,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::D,      RTD::None  , "OR D");
		instructions[0xb3].set(0xb3,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::E,      RTD::None  , "OR E");
		instructions[0xb4].set(0xb4,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::H,      RTD::None  , "OR H");
		instructions[0xb5].set(0xb5,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::L,      RTD::None  , "OR L");
		instructions[0xb6].set(0xb6,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::AddrHL, RTD::None  , "OR (HL)");
		instructions[0xb7].set(0xb7,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::A,      RTD::None  , "OR A");
		instructions[0xb8].set(0xb8,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::B,      RTD::None  , "CP B");
		instructions[0xb9].set(0xb9,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::C,      RTD::None  , "CP C");
		instructions[0xba].set(0xba,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::D,      RTD::None  , "CP D");
		instructions[0xbb].set(0xbb,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::E,      RTD::None  , "CP E");
		instructions[0xbc].set(0xbc,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::H,      RTD::None  , "CP H");
		instructions[0xbd].set(0xbd,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::L,      RTD::None  , "CP L");
		instructions[0xbe].set(0xbe,  0x0, 1,  8,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::AddrHL, RTD::None  , "CP (HL)");
		instructions[0xbf].set(0xbf,  0x0, 1,  4,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::None  , "CP A");
		instructions[0xc0].set(0xc0,  0x0, 1, 20,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNZ, RTD::None  , "RET NZ");
		instructions[0xc1].set(0xc1,  0x0, 1, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::BC,     RTD::None  , "POP BC");
		instructions[0xc2].set(0xc2,  0x0, 3, 16, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNZ, RTD::Addr16, "JP NZ,a16");
		instructions[0xc3].set(0xc3,  0x0, 3, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Addr16, RTD::None  , "JP a16");
		instructions[0xc4].set(0xc4,  0x0, 3, 24, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNZ, RTD::Addr16, "CALL NZ,a16");
		instructions[0xc5].set(0xc5,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::BC,     RTD::None  , "PUSH BC");
		instructions[0xc6].set(0xc6,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::Imm8  , "ADD A,d8");
		instructions[0xc7].set(0xc7,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 00H");
		instructions[0xc8].set(0xc8,  0x0, 1, 20,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagZ,  RTD::None  , "RET Z");
		instructions[0xc9].set(0xc9,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RET");
		instructions[0xca].set(0xca,  0x0, 3, 16, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagZ,  RTD::Addr16, "JP Z,a16");
		instructions[0xcb].set(0xcb,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "PREFIX CB");
		instructions[0xcc].set(0xcc,  0x0, 3, 24, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagZ,  RTD::Addr16, "CALL Z,a16");
		instructions[0xcd].set(0xcd,  0x0, 3, 24,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Addr16, RTD::None  , "CALL a16");
		instructions[0xce].set(0xce,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::Imm8  , "ADC A,d8");
		instructions[0xcf].set(0xcf,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 08H");
		instructions[0xd0].set(0xd0,  0x0, 1, 20,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNC, RTD::None  , "RET NC");
		instructions[0xd1].set(0xd1,  0x0, 1, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::DE,     RTD::None  , "POP DE");
		instructions[0xd2].set(0xd2,  0x0, 3, 16, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNC, RTD::Addr16, "JP NC,a16");
		instructions[0xd3].set(0xd3,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xd4].set(0xd4,  0x0, 3, 24, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagNC, RTD::Addr16, "CALL NC,a16");
		instructions[0xd5].set(0xd5,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::DE,     RTD::None  , "PUSH DE");
		instructions[0xd6].set(0xd6,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::Imm8,   RTD::None  , "SUB d8");
		instructions[0xd7].set(0xd7,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 10H");
		instructions[0xd8].set(0xd8,  0x0, 1, 20,  8, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagC,  RTD::None  , "RET CF");
		instructions[0xd9].set(0xd9,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RETI");
		instructions[0xda].set(0xda,  0x0, 3, 16, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagC,  RTD::Addr16, "JP CF,a16");
		instructions[0xdb].set(0xdb,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xdc].set(0xdc,  0x0, 3, 24, 12, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::FlagC,  RTD::Addr16, "CALL CF,a16");
		instructions[0xdd].set(0xdd,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xde].set(0xde,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::A,      RTD::Imm8  , "SBC A,d8");
		instructions[0xdf].set(0xdf,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 18H");
		instructions[0xe0].set(0xe0,  0x0, 2, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Addr8,  RTD::A     , "LDH a8,A");
		instructions[0xe1].set(0xe1,  0x0, 1, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::HL,     RTD::None  , "POP HL");
		instructions[0xe2].set(0xe2,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrC,  RTD::A     , "LD (C),A");
		instructions[0xe3].set(0xe3,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xe4].set(0xe4,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xe5].set(0xe5,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::HL,     RTD::None  , "PUSH HL");
		instructions[0xe6].set(0xe6,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Reset       , RTD::Imm8,   RTD::None  , "AND d8");
		instructions[0xe7].set(0xe7,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 20H");
		instructions[0xe8].set(0xe8,  0x0, 2, 16,  0, RFB::Reset,       RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::SP,     RTD::SImm8 , "ADD SP,r8");
		instructions[0xe9].set(0xe9,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AddrHL, RTD::None  , "JP (HL)");
		instructions[0xea].set(0xea,  0x0, 3, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Addr16, RTD::A     , "LD a16,A");
		instructions[0xeb].set(0xeb,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xec].set(0xec,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xed].set(0xed,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xee].set(0xee,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::Imm8,   RTD::None  , "XOR d8");
		instructions[0xef].set(0xef,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 28H");
		instructions[0xf0].set(0xf0,  0x0, 2, 12,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::Addr8 , "LDH A,a8");
		instructions[0xf1].set(0xf1,  0x0, 1, 12,  0, RFB::PerFunction, RFB::PerFunction, RFB::PerFunction, RFB::PerFunction , RTD::AF,     RTD::None  , "POP AF");
		instructions[0xf2].set(0xf2,  0x0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::AddrC , "LD A,(C)");
		instructions[0xf3].set(0xf3,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "DI");
		instructions[0xf4].set(0xf4,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xf5].set(0xf5,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::AF,     RTD::None  , "PUSH AF");
		instructions[0xf6].set(0xf6,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::Imm8,   RTD::None  , "OR d8");
		instructions[0xf7].set(0xf7,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 30H");
		instructions[0xf8].set(0xf8,  0x0, 2, 12,  0, RFB::Reset,       RFB::Reset,       RFB::PerFunction, RFB::PerFunction , RTD::SP,     RTD::SImm8 , "LDHL SP,r8");
		instructions[0xf9].set(0xf9,  0x0, 1,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::SP,     RTD::HL    , "LD SP,HL");
		instructions[0xfa].set(0xfa,  0x0, 3, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::A,      RTD::Addr16, "LD A,a16");
		instructions[0xfb].set(0xfb,  0x0, 1,  4,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "EI");
		instructions[0xfc].set(0xfc,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xfd].set(0xfd,  0x0, 0,  0,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "XX");
		instructions[0xfe].set(0xfe,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Set,         RFB::PerFunction, RFB::PerFunction , RTD::Imm8,   RTD::None  , "CP d8");
		instructions[0xff].set(0xff,  0x0, 1, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::None,   RTD::None  , "RST 38H");
	}
} // gbhw