#pragma once

#include "gbhw_cpu.h"

namespace gbhw
{
	GBInline void SetupInstructionsExtended(Instruction* instructions)
	{
		instructions[ 0x0].Set(0xCB,  0x0, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::B,      RTD::None  , "RLC B");
		instructions[ 0x1].Set(0xCB,  0x1, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::C,      RTD::None  , "RLC C");
		instructions[ 0x2].Set(0xCB,  0x2, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::D,      RTD::None  , "RLC D");
		instructions[ 0x3].Set(0xCB,  0x3, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::E,      RTD::None  , "RLC E");
		instructions[ 0x4].Set(0xCB,  0x4, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::H,      RTD::None  , "RLC H");
		instructions[ 0x5].Set(0xCB,  0x5, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::L,      RTD::None  , "RLC L");
		instructions[ 0x6].Set(0xCB,  0x6, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::AddrHL, RTD::None  , "RLC (HL)");
		instructions[ 0x7].Set(0xCB,  0x7, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::A,      RTD::None  , "RLC A");
		instructions[ 0x8].Set(0xCB,  0x8, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::B,      RTD::None  , "RRC B");
		instructions[ 0x9].Set(0xCB,  0x9, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::C,      RTD::None  , "RRC C");
		instructions[ 0xa].Set(0xCB,  0xa, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::D,      RTD::None  , "RRC D");
		instructions[ 0xb].Set(0xCB,  0xb, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::E,      RTD::None  , "RRC E");
		instructions[ 0xc].Set(0xCB,  0xc, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::H,      RTD::None  , "RRC H");
		instructions[ 0xd].Set(0xCB,  0xd, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::L,      RTD::None  , "RRC L");
		instructions[ 0xe].Set(0xCB,  0xe, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::AddrHL, RTD::None  , "RRC (HL)");
		instructions[ 0xf].Set(0xCB,  0xf, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::A,      RTD::None  , "RRC A");
		instructions[0x10].Set(0xCB, 0x10, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::B,      RTD::None  , "RL B");
		instructions[0x11].Set(0xCB, 0x11, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::C,      RTD::None  , "RL C");
		instructions[0x12].Set(0xCB, 0x12, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::D,      RTD::None  , "RL D");
		instructions[0x13].Set(0xCB, 0x13, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::E,      RTD::None  , "RL E");
		instructions[0x14].Set(0xCB, 0x14, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::H,      RTD::None  , "RL H");
		instructions[0x15].Set(0xCB, 0x15, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::L,      RTD::None  , "RL L");
		instructions[0x16].Set(0xCB, 0x16, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::AddrHL, RTD::None  , "RL (HL)");
		instructions[0x17].Set(0xCB, 0x17, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::A,      RTD::None  , "RL A");
		instructions[0x18].Set(0xCB, 0x18, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::B,      RTD::None  , "RR B");
		instructions[0x19].Set(0xCB, 0x19, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::C,      RTD::None  , "RR C");
		instructions[0x1a].Set(0xCB, 0x1a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::D,      RTD::None  , "RR D");
		instructions[0x1b].Set(0xCB, 0x1b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::E,      RTD::None  , "RR E");
		instructions[0x1c].Set(0xCB, 0x1c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::H,      RTD::None  , "RR H");
		instructions[0x1d].Set(0xCB, 0x1d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::L,      RTD::None  , "RR L");
		instructions[0x1e].Set(0xCB, 0x1e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::AddrHL, RTD::None  , "RR (HL)");
		instructions[0x1f].Set(0xCB, 0x1f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::A,      RTD::None  , "RR A");
		instructions[0x20].Set(0xCB, 0x20, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::B,      RTD::None  , "SLA B");
		instructions[0x21].Set(0xCB, 0x21, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::C,      RTD::None  , "SLA C");
		instructions[0x22].Set(0xCB, 0x22, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::D,      RTD::None  , "SLA D");
		instructions[0x23].Set(0xCB, 0x23, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::E,      RTD::None  , "SLA E");
		instructions[0x24].Set(0xCB, 0x24, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::H,      RTD::None  , "SLA H");
		instructions[0x25].Set(0xCB, 0x25, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::L,      RTD::None  , "SLA L");
		instructions[0x26].Set(0xCB, 0x26, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::AddrHL, RTD::None  , "SLA (HL)");
		instructions[0x27].Set(0xCB, 0x27, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::A,      RTD::None  , "SLA A");
		instructions[0x28].Set(0xCB, 0x28, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::B,      RTD::None  , "SRA B");
		instructions[0x29].Set(0xCB, 0x29, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::C,      RTD::None  , "SRA C");
		instructions[0x2a].Set(0xCB, 0x2a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::D,      RTD::None  , "SRA D");
		instructions[0x2b].Set(0xCB, 0x2b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::E,      RTD::None  , "SRA E");
		instructions[0x2c].Set(0xCB, 0x2c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::H,      RTD::None  , "SRA H");
		instructions[0x2d].Set(0xCB, 0x2d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::L,      RTD::None  , "SRA L");
		instructions[0x2e].Set(0xCB, 0x2e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::AddrHL, RTD::None  , "SRA (HL)");
		instructions[0x2f].Set(0xCB, 0x2f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::A,      RTD::None  , "SRA A");
		instructions[0x30].Set(0xCB, 0x30, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::B,      RTD::None  , "SWAP B");
		instructions[0x31].Set(0xCB, 0x31, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::C,      RTD::None  , "SWAP C");
		instructions[0x32].Set(0xCB, 0x32, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::D,      RTD::None  , "SWAP D");
		instructions[0x33].Set(0xCB, 0x33, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::E,      RTD::None  , "SWAP E");
		instructions[0x34].Set(0xCB, 0x34, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::H,      RTD::None  , "SWAP H");
		instructions[0x35].Set(0xCB, 0x35, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::L,      RTD::None  , "SWAP L");
		instructions[0x36].Set(0xCB, 0x36, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::AddrHL, RTD::None  , "SWAP (HL)");
		instructions[0x37].Set(0xCB, 0x37, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::Reset       , RTD::A,      RTD::None  , "SWAP A");
		instructions[0x38].Set(0xCB, 0x38, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::B,      RTD::None  , "SRL B");
		instructions[0x39].Set(0xCB, 0x39, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::C,      RTD::None  , "SRL C");
		instructions[0x3a].Set(0xCB, 0x3a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::D,      RTD::None  , "SRL D");
		instructions[0x3b].Set(0xCB, 0x3b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::E,      RTD::None  , "SRL E");
		instructions[0x3c].Set(0xCB, 0x3c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::H,      RTD::None  , "SRL H");
		instructions[0x3d].Set(0xCB, 0x3d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::L,      RTD::None  , "SRL L");
		instructions[0x3e].Set(0xCB, 0x3e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::AddrHL, RTD::None  , "SRL (HL)");
		instructions[0x3f].Set(0xCB, 0x3f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Reset,       RFB::PerFunction , RTD::A,      RTD::None  , "SRL A");
		instructions[0x40].Set(0xCB, 0x40, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::B     , "BIT 0,B");
		instructions[0x41].Set(0xCB, 0x41, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::C     , "BIT 0,C");
		instructions[0x42].Set(0xCB, 0x42, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::D     , "BIT 0,D");
		instructions[0x43].Set(0xCB, 0x43, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::E     , "BIT 0,E");
		instructions[0x44].Set(0xCB, 0x44, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::H     , "BIT 0,H");
		instructions[0x45].Set(0xCB, 0x45, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::L     , "BIT 0,L");
		instructions[0x46].Set(0xCB, 0x46, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::AddrHL, "BIT 0,(HL)");
		instructions[0x47].Set(0xCB, 0x47, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Zero,   RTD::A     , "BIT 0,A");
		instructions[0x48].Set(0xCB, 0x48, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::B     , "BIT 1,B");
		instructions[0x49].Set(0xCB, 0x49, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::C     , "BIT 1,C");
		instructions[0x4a].Set(0xCB, 0x4a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::D     , "BIT 1,D");
		instructions[0x4b].Set(0xCB, 0x4b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::E     , "BIT 1,E");
		instructions[0x4c].Set(0xCB, 0x4c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::H     , "BIT 1,H");
		instructions[0x4d].Set(0xCB, 0x4d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::L     , "BIT 1,L");
		instructions[0x4e].Set(0xCB, 0x4e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::AddrHL, "BIT 1,(HL)");
		instructions[0x4f].Set(0xCB, 0x4f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::One,    RTD::A     , "BIT 1,A");
		instructions[0x50].Set(0xCB, 0x50, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::B     , "BIT 2,B");
		instructions[0x51].Set(0xCB, 0x51, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::C     , "BIT 2,C");
		instructions[0x52].Set(0xCB, 0x52, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::D     , "BIT 2,D");
		instructions[0x53].Set(0xCB, 0x53, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::E     , "BIT 2,E");
		instructions[0x54].Set(0xCB, 0x54, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::H     , "BIT 2,H");
		instructions[0x55].Set(0xCB, 0x55, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::L     , "BIT 2,L");
		instructions[0x56].Set(0xCB, 0x56, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::AddrHL, "BIT 2,(HL)");
		instructions[0x57].Set(0xCB, 0x57, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Two,    RTD::A     , "BIT 2,A");
		instructions[0x58].Set(0xCB, 0x58, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::B     , "BIT 3,B");
		instructions[0x59].Set(0xCB, 0x59, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::C     , "BIT 3,C");
		instructions[0x5a].Set(0xCB, 0x5a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::D     , "BIT 3,D");
		instructions[0x5b].Set(0xCB, 0x5b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::E     , "BIT 3,E");
		instructions[0x5c].Set(0xCB, 0x5c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::H     , "BIT 3,H");
		instructions[0x5d].Set(0xCB, 0x5d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::L     , "BIT 3,L");
		instructions[0x5e].Set(0xCB, 0x5e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::AddrHL, "BIT 3,(HL)");
		instructions[0x5f].Set(0xCB, 0x5f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Three,  RTD::A     , "BIT 3,A");
		instructions[0x60].Set(0xCB, 0x60, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::B     , "BIT 4,B");
		instructions[0x61].Set(0xCB, 0x61, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::C     , "BIT 4,C");
		instructions[0x62].Set(0xCB, 0x62, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::D     , "BIT 4,D");
		instructions[0x63].Set(0xCB, 0x63, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::E     , "BIT 4,E");
		instructions[0x64].Set(0xCB, 0x64, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::H     , "BIT 4,H");
		instructions[0x65].Set(0xCB, 0x65, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::L     , "BIT 4,L");
		instructions[0x66].Set(0xCB, 0x66, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::AddrHL, "BIT 4,(HL)");
		instructions[0x67].Set(0xCB, 0x67, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Four,   RTD::A     , "BIT 4,A");
		instructions[0x68].Set(0xCB, 0x68, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::B     , "BIT 5,B");
		instructions[0x69].Set(0xCB, 0x69, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::C     , "BIT 5,C");
		instructions[0x6a].Set(0xCB, 0x6a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::D     , "BIT 5,D");
		instructions[0x6b].Set(0xCB, 0x6b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::E     , "BIT 5,E");
		instructions[0x6c].Set(0xCB, 0x6c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::H     , "BIT 5,H");
		instructions[0x6d].Set(0xCB, 0x6d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::L     , "BIT 5,L");
		instructions[0x6e].Set(0xCB, 0x6e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::AddrHL, "BIT 5,(HL)");
		instructions[0x6f].Set(0xCB, 0x6f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Five,   RTD::A     , "BIT 5,A");
		instructions[0x70].Set(0xCB, 0x70, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::B     , "BIT 6,B");
		instructions[0x71].Set(0xCB, 0x71, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::C     , "BIT 6,C");
		instructions[0x72].Set(0xCB, 0x72, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::D     , "BIT 6,D");
		instructions[0x73].Set(0xCB, 0x73, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::E     , "BIT 6,E");
		instructions[0x74].Set(0xCB, 0x74, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::H     , "BIT 6,H");
		instructions[0x75].Set(0xCB, 0x75, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::L     , "BIT 6,L");
		instructions[0x76].Set(0xCB, 0x76, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::AddrHL, "BIT 6,(HL)");
		instructions[0x77].Set(0xCB, 0x77, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Six,    RTD::A     , "BIT 6,A");
		instructions[0x78].Set(0xCB, 0x78, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::B     , "BIT 7,B");
		instructions[0x79].Set(0xCB, 0x79, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::C     , "BIT 7,C");
		instructions[0x7a].Set(0xCB, 0x7a, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::D     , "BIT 7,D");
		instructions[0x7b].Set(0xCB, 0x7b, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::E     , "BIT 7,E");
		instructions[0x7c].Set(0xCB, 0x7c, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::H     , "BIT 7,H");
		instructions[0x7d].Set(0xCB, 0x7d, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::L     , "BIT 7,L");
		instructions[0x7e].Set(0xCB, 0x7e, 2, 16,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::AddrHL, "BIT 7,(HL)");
		instructions[0x7f].Set(0xCB, 0x7f, 2,  8,  0, RFB::PerFunction, RFB::Reset,       RFB::Set,         RFB::Unmodified  , RTD::Seven,  RTD::A     , "BIT 7,A");
		instructions[0x80].Set(0xCB, 0x80, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::B     , "RES 0,B");
		instructions[0x81].Set(0xCB, 0x81, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::C     , "RES 0,C");
		instructions[0x82].Set(0xCB, 0x82, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::D     , "RES 0,D");
		instructions[0x83].Set(0xCB, 0x83, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::E     , "RES 0,E");
		instructions[0x84].Set(0xCB, 0x84, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::H     , "RES 0,H");
		instructions[0x85].Set(0xCB, 0x85, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::L     , "RES 0,L");
		instructions[0x86].Set(0xCB, 0x86, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::AddrHL, "RES 0,(HL)");
		instructions[0x87].Set(0xCB, 0x87, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::A     , "RES 0,A");
		instructions[0x88].Set(0xCB, 0x88, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::B     , "RES 1,B");
		instructions[0x89].Set(0xCB, 0x89, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::C     , "RES 1,C");
		instructions[0x8a].Set(0xCB, 0x8a, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::D     , "RES 1,D");
		instructions[0x8b].Set(0xCB, 0x8b, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::E     , "RES 1,E");
		instructions[0x8c].Set(0xCB, 0x8c, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::H     , "RES 1,H");
		instructions[0x8d].Set(0xCB, 0x8d, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::L     , "RES 1,L");
		instructions[0x8e].Set(0xCB, 0x8e, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::AddrHL, "RES 1,(HL)");
		instructions[0x8f].Set(0xCB, 0x8f, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::A     , "RES 1,A");
		instructions[0x90].Set(0xCB, 0x90, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::B     , "RES 2,B");
		instructions[0x91].Set(0xCB, 0x91, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::C     , "RES 2,C");
		instructions[0x92].Set(0xCB, 0x92, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::D     , "RES 2,D");
		instructions[0x93].Set(0xCB, 0x93, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::E     , "RES 2,E");
		instructions[0x94].Set(0xCB, 0x94, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::H     , "RES 2,H");
		instructions[0x95].Set(0xCB, 0x95, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::L     , "RES 2,L");
		instructions[0x96].Set(0xCB, 0x96, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::AddrHL, "RES 2,(HL)");
		instructions[0x97].Set(0xCB, 0x97, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::A     , "RES 2,A");
		instructions[0x98].Set(0xCB, 0x98, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::B     , "RES 3,B");
		instructions[0x99].Set(0xCB, 0x99, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::C     , "RES 3,C");
		instructions[0x9a].Set(0xCB, 0x9a, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::D     , "RES 3,D");
		instructions[0x9b].Set(0xCB, 0x9b, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::E     , "RES 3,E");
		instructions[0x9c].Set(0xCB, 0x9c, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::H     , "RES 3,H");
		instructions[0x9d].Set(0xCB, 0x9d, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::L     , "RES 3,L");
		instructions[0x9e].Set(0xCB, 0x9e, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::AddrHL, "RES 3,(HL)");
		instructions[0x9f].Set(0xCB, 0x9f, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::A     , "RES 3,A");
		instructions[0xa0].Set(0xCB, 0xa0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::B     , "RES 4,B");
		instructions[0xa1].Set(0xCB, 0xa1, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::C     , "RES 4,C");
		instructions[0xa2].Set(0xCB, 0xa2, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::D     , "RES 4,D");
		instructions[0xa3].Set(0xCB, 0xa3, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::E     , "RES 4,E");
		instructions[0xa4].Set(0xCB, 0xa4, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::H     , "RES 4,H");
		instructions[0xa5].Set(0xCB, 0xa5, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::L     , "RES 4,L");
		instructions[0xa6].Set(0xCB, 0xa6, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::AddrHL, "RES 4,(HL)");
		instructions[0xa7].Set(0xCB, 0xa7, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::A     , "RES 4,A");
		instructions[0xa8].Set(0xCB, 0xa8, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::B     , "RES 5,B");
		instructions[0xa9].Set(0xCB, 0xa9, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::C     , "RES 5,C");
		instructions[0xaa].Set(0xCB, 0xaa, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::D     , "RES 5,D");
		instructions[0xab].Set(0xCB, 0xab, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::E     , "RES 5,E");
		instructions[0xac].Set(0xCB, 0xac, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::H     , "RES 5,H");
		instructions[0xad].Set(0xCB, 0xad, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::L     , "RES 5,L");
		instructions[0xae].Set(0xCB, 0xae, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::AddrHL, "RES 5,(HL)");
		instructions[0xaf].Set(0xCB, 0xaf, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::A     , "RES 5,A");
		instructions[0xb0].Set(0xCB, 0xb0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::B     , "RES 6,B");
		instructions[0xb1].Set(0xCB, 0xb1, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::C     , "RES 6,C");
		instructions[0xb2].Set(0xCB, 0xb2, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::D     , "RES 6,D");
		instructions[0xb3].Set(0xCB, 0xb3, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::E     , "RES 6,E");
		instructions[0xb4].Set(0xCB, 0xb4, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::H     , "RES 6,H");
		instructions[0xb5].Set(0xCB, 0xb5, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::L     , "RES 6,L");
		instructions[0xb6].Set(0xCB, 0xb6, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::AddrHL, "RES 6,(HL)");
		instructions[0xb7].Set(0xCB, 0xb7, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::A     , "RES 6,A");
		instructions[0xb8].Set(0xCB, 0xb8, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::B     , "RES 7,B");
		instructions[0xb9].Set(0xCB, 0xb9, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::C     , "RES 7,C");
		instructions[0xba].Set(0xCB, 0xba, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::D     , "RES 7,D");
		instructions[0xbb].Set(0xCB, 0xbb, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::E     , "RES 7,E");
		instructions[0xbc].Set(0xCB, 0xbc, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::H     , "RES 7,H");
		instructions[0xbd].Set(0xCB, 0xbd, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::L     , "RES 7,L");
		instructions[0xbe].Set(0xCB, 0xbe, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::AddrHL, "RES 7,(HL)");
		instructions[0xbf].Set(0xCB, 0xbf, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::A     , "RES 7,A");
		instructions[0xc0].Set(0xCB, 0xc0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::B     , "SET 0,B");
		instructions[0xc1].Set(0xCB, 0xc1, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::C     , "SET 0,C");
		instructions[0xc2].Set(0xCB, 0xc2, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::D     , "SET 0,D");
		instructions[0xc3].Set(0xCB, 0xc3, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::E     , "SET 0,E");
		instructions[0xc4].Set(0xCB, 0xc4, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::H     , "SET 0,H");
		instructions[0xc5].Set(0xCB, 0xc5, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::L     , "SET 0,L");
		instructions[0xc6].Set(0xCB, 0xc6, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::AddrHL, "SET 0,(HL)");
		instructions[0xc7].Set(0xCB, 0xc7, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Zero,   RTD::A     , "SET 0,A");
		instructions[0xc8].Set(0xCB, 0xc8, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::B     , "SET 1,B");
		instructions[0xc9].Set(0xCB, 0xc9, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::C     , "SET 1,C");
		instructions[0xca].Set(0xCB, 0xca, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::D     , "SET 1,D");
		instructions[0xcb].Set(0xCB, 0xcb, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::E     , "SET 1,E");
		instructions[0xcc].Set(0xCB, 0xcc, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::H     , "SET 1,H");
		instructions[0xcd].Set(0xCB, 0xcd, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::L     , "SET 1,L");
		instructions[0xce].Set(0xCB, 0xce, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::AddrHL, "SET 1,(HL)");
		instructions[0xcf].Set(0xCB, 0xcf, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::One,    RTD::A     , "SET 1,A");
		instructions[0xd0].Set(0xCB, 0xd0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::B     , "SET 2,B");
		instructions[0xd1].Set(0xCB, 0xd1, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::C     , "SET 2,C");
		instructions[0xd2].Set(0xCB, 0xd2, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::D     , "SET 2,D");
		instructions[0xd3].Set(0xCB, 0xd3, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::E     , "SET 2,E");
		instructions[0xd4].Set(0xCB, 0xd4, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::H     , "SET 2,H");
		instructions[0xd5].Set(0xCB, 0xd5, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::L     , "SET 2,L");
		instructions[0xd6].Set(0xCB, 0xd6, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::AddrHL, "SET 2,(HL)");
		instructions[0xd7].Set(0xCB, 0xd7, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Two,    RTD::A     , "SET 2,A");
		instructions[0xd8].Set(0xCB, 0xd8, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::B     , "SET 3,B");
		instructions[0xd9].Set(0xCB, 0xd9, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::C     , "SET 3,C");
		instructions[0xda].Set(0xCB, 0xda, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::D     , "SET 3,D");
		instructions[0xdb].Set(0xCB, 0xdb, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::E     , "SET 3,E");
		instructions[0xdc].Set(0xCB, 0xdc, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::H     , "SET 3,H");
		instructions[0xdd].Set(0xCB, 0xdd, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::L     , "SET 3,L");
		instructions[0xde].Set(0xCB, 0xde, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::AddrHL, "SET 3,(HL)");
		instructions[0xdf].Set(0xCB, 0xdf, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Three,  RTD::A     , "SET 3,A");
		instructions[0xe0].Set(0xCB, 0xe0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::B     , "SET 4,B");
		instructions[0xe1].Set(0xCB, 0xe1, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::C     , "SET 4,C");
		instructions[0xe2].Set(0xCB, 0xe2, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::D     , "SET 4,D");
		instructions[0xe3].Set(0xCB, 0xe3, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::E     , "SET 4,E");
		instructions[0xe4].Set(0xCB, 0xe4, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::H     , "SET 4,H");
		instructions[0xe5].Set(0xCB, 0xe5, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::L     , "SET 4,L");
		instructions[0xe6].Set(0xCB, 0xe6, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::AddrHL, "SET 4,(HL)");
		instructions[0xe7].Set(0xCB, 0xe7, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Four,   RTD::A     , "SET 4,A");
		instructions[0xe8].Set(0xCB, 0xe8, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::B     , "SET 5,B");
		instructions[0xe9].Set(0xCB, 0xe9, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::C     , "SET 5,C");
		instructions[0xea].Set(0xCB, 0xea, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::D     , "SET 5,D");
		instructions[0xeb].Set(0xCB, 0xeb, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::E     , "SET 5,E");
		instructions[0xec].Set(0xCB, 0xec, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::H     , "SET 5,H");
		instructions[0xed].Set(0xCB, 0xed, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::L     , "SET 5,L");
		instructions[0xee].Set(0xCB, 0xee, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::AddrHL, "SET 5,(HL)");
		instructions[0xef].Set(0xCB, 0xef, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Five,   RTD::A     , "SET 5,A");
		instructions[0xf0].Set(0xCB, 0xf0, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::B     , "SET 6,B");
		instructions[0xf1].Set(0xCB, 0xf1, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::C     , "SET 6,C");
		instructions[0xf2].Set(0xCB, 0xf2, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::D     , "SET 6,D");
		instructions[0xf3].Set(0xCB, 0xf3, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::E     , "SET 6,E");
		instructions[0xf4].Set(0xCB, 0xf4, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::H     , "SET 6,H");
		instructions[0xf5].Set(0xCB, 0xf5, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::L     , "SET 6,L");
		instructions[0xf6].Set(0xCB, 0xf6, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::AddrHL, "SET 6,(HL)");
		instructions[0xf7].Set(0xCB, 0xf7, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Six,    RTD::A     , "SET 6,A");
		instructions[0xf8].Set(0xCB, 0xf8, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::B     , "SET 7,B");
		instructions[0xf9].Set(0xCB, 0xf9, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::C     , "SET 7,C");
		instructions[0xfa].Set(0xCB, 0xfa, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::D     , "SET 7,D");
		instructions[0xfb].Set(0xCB, 0xfb, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::E     , "SET 7,E");
		instructions[0xfc].Set(0xCB, 0xfc, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::H     , "SET 7,H");
		instructions[0xfd].Set(0xCB, 0xfd, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::L     , "SET 7,L");
		instructions[0xfe].Set(0xCB, 0xfe, 2, 16,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::AddrHL, "SET 7,(HL)");
		instructions[0xff].Set(0xCB, 0xff, 2,  8,  0, RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified,  RFB::Unmodified  , RTD::Seven,  RTD::A     , "SET 7,A");
	}
} // gbhw